### ISSUE TITLE
`go get` command not working

### ISSUE THREAD

**Issue by Tomperez98** [temporalio/edu-101-go-code#1]
### `go env`

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tomasperez/Library/Caches/go-build"
GOENV="/Users/tomasperez/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tomasperez/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tomasperez/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.7"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tomasperez/Documents/Personal/courses/edu-101-go-code/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mx/n4wnqc9x6l9cthf453jy351c0000gn/T/go-build822001193=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

Then, when I run `go get` this is the output
```
go: no package to get in the current directory
```

**Comment by tomwheeler** [comment]
Tomas, thank you for including the `go env` output, which helps me to better understand your environment. However, it wasn't clear from the issue whether `go get` was the complete command you ran when you encountered this error, nor did you specify the directory from which you ran it. I think those details will help me confirm the root cause. 

I was able to produce the same error message you reported when running `go get` (i.e., without any arguments) from the root directory of my local clone of the code repository. However, the command (`go get go.temporal.io/sdk`) shown in the "How to Install the Go SDK" section works as expected for me when executed from that same directory. If executed from a directory without a Go module, the latter command produces a different error (as expected). 

Could you please update this issue to include the specific command you ran and the directory path where you executed this command? Once I have this, I should be able to better explain the problem, as well as the solution.

**Comment by tomwheeler** [comment]
I meant to add that I've now added a placeholder program to the project root, so running "go get" without arguments should no longer result in an warning.

**Comment by Tomperez98** [comment]
I confirm. Now, `go get` does not produce any warning.

I'll keep in mind adding `cwd` and being more explicit about the command being run.

Thanks
